name: Test
on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2

          - name: Build packages
            uses: icepuma/rust-action@master
            with:
                args: |
                    apt update && apt install -y libfuse-dev pkg-config && cargo build --release

          - name: Detect /dev/fuse
            run: |
                ls -alF /dev/fuse

          - name: Test mount
            run: |
                mkdir /tmp/aha
                target/release/fuse-ci-test /tmp/aha --auto_unmount &
                sleep 1
                (mount | grep /tmp/aha) || echo Not found
                ls -alF /tmp/aha
                ls -Z /tmp/aha
                cat /tmp/aha/hello.txt
                umount /tmp/aha

          - name: Upload binary file
            uses: actions/upload-artifact@v2
            with:
                name: Binary
                path: |
                    target/release/fuse-ci-test
